### PR TITLE
Add support for Arch-based distros

### PR DESCRIPTION
**Pull request by AkikoKumagara**
This is done by checking if `apt` command exists, then falling back on `pacman` if it does not, and otherwise failing as usual.
I've also changed the deprecated `convert` command to the current `magick` command, which works the same but under a different name.
This method I've used should also make it simple to add support for other package managers (as needed).

I have tested the updated setup script on both Debian and Arch Linux.

### CODE REVIEW

**Comment by AkikoKumagara** [comment]
May require some formatting work as I was mostly concerned about functionality, but should work great. Also that packages needed line was left in by mistake (lol), that doesn't do anything and isn't called anywhere.

**Comment by CosmicScale** [comment]
Hi, I hope you had a great Christmas! I finally got some time to look at this.

I tried running the setup script on an EndeavourOS live environment, but I encountered numerous 404 errors. Running `sudo pacman -Syu` before executing the script resolved the issue. Is there an easier way to get this working on a live environment without requiring a full update? On Debian, it was as simple as editing /etc/apt/sources.list.

Also, running `magick` on Linux Mint results in a 'command not found' error. It’s better to stick with `convert`, as it works on both distributions.

**Comment by AkikoKumagara** [comment]
Gotcha, I'll see if I can find a better way for live compat on Arch.
I guess magick isn't ready quite yet, but that'll probably be a change to make down the road.

**Comment by AkikoKumagara** [comment]
OK, all noted issues should be resolved now. Please test for yourself on your Arch-based live environment again if you don't mind.

**Comment by CosmicScale** [comment]
Okay, everything works. I updated the readme and added python3, bc and rsync to apt install. Looks like it pushed to your fork but is not showing up in this PR. No idea what I'm doing wrong, never had to deal with a PR before lol

**Comment by AkikoKumagara** [comment]
I don't see your contribution anywhere either 😅

**Comment by CosmicScale** [comment]
Merged! I'll just add my changes after. Thanks for the contribution :)

**Pull request merged**
